server:
  port: 8082   # adapte au port réel

spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: travel_app_user
    password: MON_MOT_DE_PASSE_DB
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/travel-realm

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
