# FICHIER 2 : application.yml (Vol-Service)
spring:
  application:
    name: vol-service # Nom nécessaire pour les logs

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    # Ces lignes sont maintenant GÉRÉES par bootstrap.yml ou le fichier Git
    register-with-eureka: true
    fetch-registry: true

# TOUTES LES INFOS ORACLE/JPA SONT ABSENTES ICI