server:
port: 8888 # Port standard pour le Config Server

spring:
application:
name: config-service
cloud:
config:
git:
# VEUILLEZ REMPLACER PAR L'URL DE VOTRE DÉPÔT GIT DE CONFIGURATION
# Si vous n'avez pas de dépôt dédié, utilisez le chemin local d'un dossier
uri: file:///C:/Users/HP/Downloads/ItPay_backend-master/travel_booking_system/config-repo # OU (si vous utilisez un dossier local dans le projet parent) :
# uri: file:///C:/Users/HP/Downloads/ItPay_backend-master/config-repo

# Configuration Eureka Client
eureka:
client:
service-url:
defaultZone: http://127.0.0.1:8761/eureka/